- stable/cert-manager-istio-controller/Chart.yaml
- stable/cert-manager-istio-controller/templates/deployment.yaml
This causes the pod to continuously restart
> fix(cert-manager-istio-controller): Remove liveness and readiness probes

- stable/ckan/Chart.yaml
- stable/ckan/templates/deploy/ckan.yaml
- stable/ckan/templates/secret/ckan.yaml
- stable/ckan/values.yaml
- Added to values.yml and ckan.yml (correctly, I hope...)
- Value to be used here: https://gitlab.k8s.cloud.statcan.ca/analytics-platform/codas-ckan/ckanext-util/-/blob/master/ckanext/util/config.yaml
> Create the Azure Client Secret to be used in ckanext-util

- stable/ckan/Chart.yaml
- stable/ckan/templates/deploy/ckan.yaml
- stable/ckan/templates/secret/ckan-ckanext-util.yaml
- stable/ckan/templates/secret/ckan.yaml
- stable/ckan/values.yaml
- Fixed an issue where the env var was being set but not seen during deployment (new secret was under psql whe it should have been under env)
> Quick change to azure client secret placement

- stable/orchard-cms/Chart.yaml
- stable/orchard-cms/README.md
- stable/orchard-cms/templates/_helpers.tpl
- stable/orchard-cms/templates/deployment.yaml
- stable/orchard-cms/templates/secret.yaml
- stable/orchard-cms/values.yaml
Adds support for mapping environment variables from a secret
Breaking: removes automatic postgresql variables injection
> feat: secret environment variables

- stable/varnish/Chart.yaml
- stable/varnish/templates/deploy/varnish.yaml
The current chart appear to support teloration and nodeSelector based on the included default values.yaml... but the plumbing to do so is missing.
> Adding handling of toleration and nodeSelector to chart

- stable/disclosure-vetting-application/Chart.yaml
- stable/disclosure-vetting-application/templates/db-cronjob.yaml
- stable/disclosure-vetting-application/values.yaml
First draft for vetting cronjob support
> Vetting cronjob support

- stable/disclosure-vetting-application/templates/db-cronjob.yaml
> cron-job update

- stable/disclosure-vetting-application/Chart.yaml
- stable/disclosure-vetting-application/templates/db-cronjob.yaml
> updated job

- stable/ckan/Chart.yaml
- stable/ckan/templates/deploy/ckan.yaml
- stable/ckan/values.yaml
- added value for sdmx transfer api version for deployment
- increment chart value
> feat:(ckan) add sdmx transfer api version

- stable/profiles-controller/Chart.yaml
- stable/profiles-controller/templates/clusterrole.yaml
> fix(profiles-controller): add ml-pipeline bind to rbac

- stable/ckan/Chart.yaml
- stable/ckan/conf/ckan/prerun.py
- fixed a AttributeError with trying to decode something that is already decoded
- changed potential problem url that is no longer being recognized
- increment chart to 17
> fix(ckan) check_solr_connection failure

- stable/fdi-dotstatsuite/templates/cm/mssql.yaml
- stable/fdi-dotstatsuite/values.yaml
Added sa_user values.yaml and to config map.  This helps with deployment.  It was hardcoded before.
Removed default value sapassword for mssql-linux.  
Small fixes in values file
> .StatSuite updates

- stable/profiles-controller/Chart.yaml
- stable/profiles-controller/templates/deployment-authpolicies.yaml
- stable/profiles-controller/templates/deployment-buckets.yaml
- stable/profiles-controller/templates/deployment-limitranges.yaml
- stable/profiles-controller/templates/deployment-network.yaml
- stable/profiles-controller/templates/deployment-notebook.yaml
- stable/profiles-controller/templates/deployment-quotas.yaml
- stable/profiles-controller/templates/deployment-rbac.yaml
- stable/profiles-controller/values.yaml
Apart of https://github.com/StatCan/aaw-kubeflow-profiles-controller/issues/17 
Added REQUEUE_TIME env var to all deployment files.
> feat(add): requeue env var to profiles-controller

- stable/namespace-controller/values.yaml
Unable to pull chart because repo name must be lowercase.
> fix: repo name case

- stable/profiles-controller/Chart.yaml
- stable/profiles-controller/templates/clusterrole.yaml
- stable/profiles-controller/templates/configmap-blob-csi-mounts.yaml
- stable/profiles-controller/templates/deployment-blob-csi.yaml
- stable/profiles-controller/values.yaml
Closes https://github.com/StatCan/daaas/issues/1022
> feat(blob-csi): add blob-csi component

- stable/fdi-dotstatsuite/templates/cm/nsidesign-log4net.yaml
- stable/fdi-dotstatsuite/templates/cm/nsistaging-log4net.yaml
- stable/fdi-dotstatsuite/values.yaml
> fix: Fdi dotstatsuite logging config

- stable/profiles-controller/Chart.yaml
- stable/profiles-controller/values.yaml
Update blobcsi config to reflect https://github.com/StatCan/aaw-argocd-manifests/blob/aaw-dev-cc-00/daaas-system/profile-controllers/profiles-controller/application.jsonnet#L62
> update: blobcsi config

- stable/fluentd-operator/crds/fluentdconfigs.yaml
Correct syntax error in fluentd crd chart
> Add CRD to fluentd chart systax error

- stable/profiles-controller/Chart.yaml
- stable/profiles-controller/values.yaml
remove: blob-csi secret name env var
> bump: profiles-controller chart

- stable/profiles-controller/Chart.yaml
Related to https://github.com/StatCan/daaas/issues/1449
> Update chart version

- stable/profiles-controller/values.yaml
PArt of https://github.com/StatCan/daaas/issues/1449
> Update profile controller sha

- stable/profiles-controller/Chart.yaml
Part of https://github.com/StatCan/daaas/issues/1449
I think the sha was update after the last version bump
> Bump chart version

- stable/profiles-controller/Chart.yaml
- stable/profiles-controller/values.yaml
Modify logic in blob-csi controller to accomodate individual Service Principals for FDI containers
> chore: bump profiles-controller chart version

- stable/profiles-controller/Chart.yaml
- stable/profiles-controller/values.yaml
revert kf-rolebinding https://github.com/StatCan/aaw-kubeflow-profiles-controller/pull/84
> revert(profiles-controller): kf-pipeline rolebinding

- stable/disclosure-vetting-application/Chart.yaml
- stable/disclosure-vetting-application/templates/secret/configmodule_py.yaml
> Secure session cookie

- stable/fdi-eck/Chart.yaml
- stable/fdi-eck/templates/fluentd-config.yaml
- stable/fdi-eck/values.yaml
- Updated the fluentd configmap to include variables for filtering container name and logs in Elastic
- Removed unnecessary logs displayed in Elastic Search for AAW dev environment
> fdi-eck fluentd configmap update

- stable/fdi-dotstatsuite-de-dv/Chart.yaml
- stable/fdi-dotstatsuite-de-dv/templates/ing/data-explorer.yaml
- stable/fdi-dotstatsuite-de-dv/templates/ing/data-view.yaml
- stable/fdi-dotstatsuite-de-dv/values.yaml
- stable/fdi-dotstatsuite-dlm/templates/ing/data-lifecycle-manager.yaml
- stable/fdi-dotstatsuite-dlm/values.yaml
- stable/fdi-eck/Chart.yaml
- stable/fdi-eck/templates/cm/fluentd-config.yaml
- stable/fdi-eck/templates/deploy/elastic.yaml
- stable/fdi-eck/templates/deploy/kibana.yaml
- stable/fdi-eck/templates/in/elastic_ingress.yaml
- stable/fdi-eck/templates/in/kibana_ingress.yaml
- stable/fdi-eck/values.yaml
added elastic.yaml, kibana.yaml, elastic_ingress.yaml, kibana_ingress.yaml
removed password from values.yaml
incremented chart to 0.3.0
> update: fdi-eck 0.3.0

- stable/profiles-controller/templates/deployment-aaw-trino-schema.yaml
- stable/profiles-controller/values.yaml
Deploy trino-schema controller
> add: deploy trino-schema controller

- stable/profiles-controller/Chart.yaml
- stable/profiles-controller/templates/deployment-aaw-trino.yaml
- stable/profiles-controller/values.yaml
bump version of pfp controller chart
https://github.com/StatCan/aaw-kubeflow-profiles-controller/commit/13bda7e424f2d54cd77f628ea5fb1d36a4b708a8
> feat(profiles-controller): bump chart, image version

- stable/istio-ingress-gateway/Chart.yaml
- stable/istio-ingress-gateway/templates/envoyfilter-hsts.yaml
Fix potential issue of envoyfilter not being applied due to relative operation without priority. https://istio.io/latest/docs/reference/config/analysis/ist0151/
> fix(istio-ingress-gateway): fix envoyfilter operation.

- stable/profiles-controller/Chart.yaml
- stable/profiles-controller/values.yaml
Related to https://github.com/StatCan/daaas/issues/1499
> Chore remove pipelines

- stable/profiles-controller/values.yaml
add: trino env vars for dev/prod customization
> add: trino env vars

- stable/sidecar-terminator/Chart.yaml
- stable/sidecar-terminator/templates/_helpers.tpl
- stable/sidecar-terminator/templates/clusterrole.yaml
- stable/sidecar-terminator/templates/deployment.yaml
- stable/sidecar-terminator/values.yaml
Update to align with https://github.com/StatCan/kubernetes-sidecar-terminator/pull/1
> feat(sidecar-terminator): update to align with new version.

- stable/hive-metastore/Chart.yaml
- stable/hive-metastore/templates/statefulset.yaml
Create a hive helm chart release
> create: hive helm release

- stable/trino/Chart.yaml
- stable/trino/templates/configmap-catalog.yaml
- stable/trino/templates/configmap-coordinator.yaml
- stable/trino/templates/configmap-worker.yaml
- stable/trino/templates/deployment-coordinator.yaml
- stable/trino/templates/deployment-worker.yaml
- stable/trino/values.yaml
Remove JMX connector for protb - re-enable at a later time
> update: remove jmx connector for protb

- stable/fdi-eck/Chart.yaml
- stable/fdi-eck/templates/deploy/elastic.yaml
- stable/fdi-eck/values.yaml
Minor change reducing size of elastic search
> storage var added

- stable/fdi-eck/Chart.yaml
- stable/fdi-eck/templates/deploy/elastic.yaml
-Secret Key ref deletion 
- Version update
> Minor Changes

- stable/profiles-controller/Chart.yaml
- stable/profiles-controller/values.yaml
- remove unused env vars
- Update helm chart with refactored blob-csi controller
> update(blob-csi): blob-csi refactored controller

- stable/profiles-controller/Chart.yaml
- stable/profiles-controller/values.yaml
update profiles-controller chart to include https://github.com/StatCan/aaw-kubeflow-profiles-controller/pull/110
> remove blob-csi-mounts poddefault

- stable/trino/Chart.yaml
- stable/trino/templates/deployment-coordinator.yaml
- stable/trino/templates/deployment-worker.yaml
Fix trino deployment; mount only 1 rules file
> fix: trino chart deployments

- stable/profiles-controller/Chart.yaml
- stable/profiles-controller/values.yaml
to add https://github.com/StatCan/aaw-kubeflow-profiles-controller/pull/116
> updated profiles controller

- stable/ckan/Chart.yaml
- stable/ckan/conf/ckan/overlay-production.ini
- stable/ckan/templates/_helpers.tpl
- stable/ckan/templates/cm/ckan-overlay.yaml
- stable/ckan/templates/cm/ckan-prerun.yaml
- stable/ckan/templates/cm/psql-init.yaml
- stable/ckan/templates/cm/solr-configset.yaml
- stable/ckan/templates/cm/solr-init.yaml
- stable/ckan/templates/cronjob/ckan.yaml
- stable/ckan/templates/deploy/ckan.yaml
- stable/ckan/templates/ing/ckan.yaml
- stable/ckan/templates/pvc/pvc.yaml
- stable/ckan/templates/sa/ckan.yaml
- stable/ckan/templates/secret/pgbouncer.yaml
- stable/ckan/templates/svc/ckan.yaml
- stable/ckan/values.yaml
- stable/fdi-dotstatsuite-tenants-vs/.helmignore
- stable/fdi-dotstatsuite-tenants-vs/Chart.yaml
- stable/fdi-dotstatsuite-tenants-vs/templates/_helpers.tpl
- stable/fdi-dotstatsuite-tenants-vs/templates/vs/tenant.yaml
- stable/fdi-dotstatsuite-tenants-vs/values.yaml
- stable/fdi-eck/templates/cm/fluentd-config.yaml
- stable/fdi-eck/templates/deploy/elastic.yaml
- stable/fdi-eck/templates/deploy/kibana.yaml
- stable/fdi-eck/values.yaml
changed made based on the review
> Fdi add virtualservices

- stable/profiles-controller/Chart.yaml
- stable/profiles-controller/values.yaml
publish https://github.com/StatCan/aaw-kubeflow-profiles-controller/actions/runs/4917020898/jobs/8781631705
> fix(profiles-controller): update jfrog netpols

- stable/profiles-controller/Chart.yaml
- stable/profiles-controller/values.yaml
Updates the profiles-controller chart
Updates the ro-container's config in the chart values
> fix(blob): update ro-container config and profiles controller sha

- stable/fdi-dotstatsuite/Chart.yaml
- stable/fdi-dotstatsuite/templates/deploy/authz.yaml
- stable/fdi-dotstatsuite/templates/deploy/nsidesign.yaml
- stable/fdi-dotstatsuite/templates/deploy/nsireset.yaml
- stable/fdi-dotstatsuite/templates/deploy/nsistable.yaml
- stable/fdi-dotstatsuite/templates/deploy/nsistaging.yaml
- stable/fdi-dotstatsuite/templates/deploy/transfer.yaml
- stable/fdi-dotstatsuite/values.yaml
> Codas 1708

- stable/profiles-controller/Chart.yaml
- stable/profiles-controller/values.yaml
Related to https://github.com/StatCan/aaw/issues/1789
> Chore bump profile controller

- stable/profiles-controller/Chart.yaml
- stable/profiles-controller/values.yaml
see https://github.com/StatCan/aaw-kubeflow-profiles-controller/pull/126
Sha: https://github.com/StatCan/aaw-kubeflow-profiles-controller/actions/runs/5754303297/job/15599307675#step:4:1
> feat(profiles-controller): update chart

- stable/profiles-controller/Chart.yaml
- stable/profiles-controller/values.yaml
Deploys https://github.com/StatCan/aaw-kubeflow-profiles-controller/commit/4c04ae634e7530852cbcc8aa1396f8c9ae244a74
> feat(profiles-controller): update chart to 4c04ae6

- stable/profiles-controller/Chart.yaml
- stable/profiles-controller/values.yaml
Deploys https://github.com/StatCan/aaw-kubeflow-profiles-controller/pull/136
> feat(profiles-controller): update chart to 907faa4

- stable/profiles-controller/Chart.yaml
- stable/profiles-controller/values.yaml
Closes https://github.com/StatCan/aaw/issues/1848
> Update sha profile controller

- stable/profiles-controller/Chart.yaml
- stable/profiles-controller/values.yaml
Closes https://github.com/StatCan/aaw/issues/1871
> Chore(profile-controller): update version and sha

- stable/fdi-dotstatsuite/Chart.yaml
- stable/fdi-dotstatsuite/templates/deploy/authz.yaml
- stable/fdi-dotstatsuite/templates/deploy/nsidesign.yaml
- stable/fdi-dotstatsuite/templates/deploy/nsireset.yaml
- stable/fdi-dotstatsuite/templates/deploy/nsistable.yaml
- stable/fdi-dotstatsuite/templates/deploy/nsistaging.yaml
- stable/fdi-dotstatsuite/templates/deploy/transfer.yaml
update deploy six yaml files bash to sh
> update(fdi-dotstatsuite): deploy yaml files bash to sh

- stable/nvidia-device-plugin/values.yaml
See https://github.com/StatCan/aaw/issues/1869#issuecomment-1838699801 for more details
> chore(nvidia gpu): update option

- stable/fdi-dotstatsuite/Chart.yaml
- stable/fdi-dotstatsuite/templates/deploy/transfer.yaml
> Fix fdi-dotstatsuite chart deployment error due to missing quotes
